### ISSUE TITLE
Reduction of parameters in loop

### ISSUE THREAD

**Issue by peonor** [Q2MM/q2mm#27]
Found a brand new bug, running with 118 parameters. First time through the loop works well, Smiplex runs with 10 parameters, as expected, but second time into Gradient uses only 10 parameters!

**Comment by ericchansen** [comment]
Guess we spoke too soon. Running tests now to try and recreate this. If you could attach your log that'd be helpful.

**Comment by peonor** [comment]
Coming here:
[tmp.txt](https://github.com/Q2MM/q2mm/files/359680/tmp.txt)

**Comment by ericchansen** [comment]
Here's what I have so far.

1. **Simplex finishes with improvements** Seems to be working.
1. **Simplex finishes without improvements** Seems to be working.
1. **Simplex encounters a ParamError exception** Seems to be working. I think this implies that all other exceptions should work because they're all handled the same way.

Let me look through that log.

**Comment by peonor** [comment]
Forgot the COMP again, could that have anything to do with it?

**Comment by peonor** [comment]
Trying the same w/o SIMP now

**Comment by ericchansen** [comment]
I don't think `COMP` would interact with this.

**Comment by ericchansen** [comment]
Ah there's something odd happening when the simplex best score is the exact same as the initial FF score.

**Comment by peonor** [comment]
I guess I need to look in the Simplex details again also, it's almost inconcievable that with a large number of parameters with negative 2nd derivative, the Simplex should fail to find any improvement.

**Comment by ericchansen** [comment]
I haven't heard about this in awhile, so I'm going to assume that the changes that occurred in relation to other issues corrected this.
