### ISSUE TITLE
Wrong parameters used for final comparison to output individual scores 

### ISSUE THREAD

**Issue by jeherr** [Q2MM/q2mm#61]
Per @peonor 

Q2MM is using the wrong FF for the final compare to output the file of individual scores. It is using the last trial FF instead of the original, "best" FF.

**Comment by jeherr** [comment]
I just want to clarify here. You say that the final compare should use the original "best" FF. What do you mean by "original"? I think what you're saying is that, after optimizing the FF parameters has converged, the best set of parameters seen throughout the whole optimization should be restored to the FF file before this comparison is done, but that isn't happening until some point _after_ the comparison, so this is being done with whatever the last trial set of parameters was, and then the "best" are being restored after this. Is that correct?

**Comment by peonor** [comment]
Hi John,

I’m not sure what you’re responding to here, I can’t find that wording in my emails. Is this a response to something Emily wrote? If so, I don’t think I saw it. One problem is simple: in the loop, Q2MM will report a score for a trial force field. If you take exactly the same force field and calculate the score with the same comparison outside the loop, you get a different value. This is not good. I believe Emily sent an example showing this.

/Per-Ola

**Comment by peonor** [comment]
Per-Ola, yes, this is a response to something I sent. John, in the particular case that I sent the files for, none of the trial FFs were better than the starting FF, so that is what I meant by “original” in this case. I have seen this in some other cases as well and your description sounds correct. The problem Per-Ola mentions doesn’t seem to be what’s happening in this case, but it does relate to the case we sent a few weeks ago.

Emily

From: Norrby, Per-Ola
Sent: den 4 oktober 2019 08:58
To: Q2MM/q2mm <reply@reply.github.com>
Cc: Tharnish, Emily (Notre Dame of Maryland University) <emily.tharnish@astrazeneca.com>; John Herr <John.E.Herr.16@nd.edu>
Subject: RE: [Q2MM/q2mm] Wrong parameters used for final comparison to output individual scores (#61)

Hi John,

I’m not sure what you’re responding to here, I can’t find that wording in my emails. Is this a response to something Emily wrote? If so, I don’t think I saw it. One problem is simple: in the loop, Q2MM will report a score for a trial force field. If you take exactly the same force field and calculate the score with the same comparison outside the loop, you get a different value. This is not good. I believe Emily sent an example showing this.

/Per-Ola

**Comment by jeherr** [comment]
Ok, after some looking into this with @jesswahlers, I think we figured out where this issue is. Whenever Jess runs any optimization, she always follows a GRAD with a SIMPLEX in the optimization loop. [At the end of simplex.run()](https://github.com/Q2MM/q2mm/blob/c67b6b1f19178e7adb6dcecbe78c1ef951dd71bc/q2mm/simplex.py#L401) the best_ff is always exported before returning the best_ff internally back to loop.py. If you look at [the end of gradient.run()](https://github.com/Q2MM/q2mm/blob/c67b6b1f19178e7adb6dcecbe78c1ef951dd71bc/q2mm/gradient.py#L330) at no point does it actually export the best_ff before returning it internally to loop.py.

So this bug never showed up before because 1) Nobody checked that running strictly gradient based optimization actually had the same final score as the best FF since whenever this bug was introduced and 2) There way always a simplex optimization step run after the gradient optimization, so the best FF was always written to mm3.fld by simplex.run() and it didn't matter that gradient.run() never overwrote the file.
