### ISSUE TITLE
Not picking up changes in gradient.py

### ISSUE THREAD

**Issue by arosale4** [Q2MM/q2mm#7]
I saw this commit, https://github.com/Q2MM/q2mm/commit/51264750341d02426e6f6cdd314b2cd4e80436de, where the code checks to see if there are any changes. Have we figured out why there are no changes? I have seen instances where a parameter does change the penalty function, and it produces changes in the do_method function, but those changes are not picked up again in the run function.

**Comment by ericchansen** [comment]
I'm really confused. Commit 51264750341d024 only removed options that generated MacroModel conformational search .com files.

**Comment by arosale4** [comment]
0cd6a70c5ab9eea4a37edb221585fa19042c4722
Thats weird, try this one.
But I think I know whats wrong:
The check function goes through the radii and cutoffs, but we currently have them defined as none.

**Comment by ericchansen** [comment]
I'm not sure what you're talking about as a bug still.

Here's an example of how things work. Maybe this will help you.

```
changes = do_lstsq(ma, vb, radii=radii, cutoffs=cutoffs)
```

This 1st goes through ```do_method``` since ```do_lstsq``` is wrapped by that function. If ```opt.OptError``` is raised, a warning is issued, and no changes are returned. This may be more clear if I added in a line ```return None``` following [line 352](https://github.com/ericchansen/q2mm/blob/9803ad01459cade44f80074f64aa4c8ee00f4bd1/gradient.py#L352), but that's also unnecessary extra line.

If ```opt.OptError``` isn't raised, then it goes through [```check```](https://github.com/ericchansen/q2mm/blob/9803ad01459cade44f80074f64aa4c8ee00f4bd1/gradient.py#L273-L290). It calculates [```radius```](https://github.com/ericchansen/q2mm/blob/9803ad01459cade44f80074f64aa4c8ee00f4bd1/gradient.py#L276), the radius of parameter change, and then either checks for maximum radii or cutoffs.

The maximum radii method essentially scales all parameter changes to be within [whatever radii is given by the user](https://github.com/ericchansen/q2mm/blob/9803ad01459cade44f80074f64aa4c8ee00f4bd1/gradient.py#L89). The user can specify as many max radii as he or she wants. If the calculated [```radius```](https://github.com/ericchansen/q2mm/blob/9803ad01459cade44f80074f64aa4c8ee00f4bd1/gradient.py#L276) is larger than those specified by the user, it will keep scaling the parameter changes to meet the user specified radii, each time generating another trial FF. It checks in order of smaller to larger user inputted maximum radii. If at some point during this process, the calculated ```radius``` is less than the user inputted maximum radius, then it returns the unscaled parameter changes. If the calculated ```radius``` starts out smaller than the smallest user requested maximum radius, then it simply returns the original, unscaled trial parameter changes. This check doesn't return ```None``` or ```0```, it will always give you something assuming ```opt.OptError``` wasn't raised earlier.

If you instead use [```check_cutoffs```](https://github.com/ericchansen/q2mm/blob/9803ad01459cade44f80074f64aa4c8ee00f4bd1/gradient.py#L292-L310) (which happens when the user doesn't specify any maximum radii and does specify [cutoffs](https://github.com/ericchansen/q2mm/blob/9803ad01459cade44f80074f64aa4c8ee00f4bd1/gradient.py#L88)), and it returns ```False```, then ```check``` and ```do_method``` returns ```[]``` (```None```, ```False``` and ```[]``` all mean ```0``` in Python).

So, ```opt.OptError``` (troublesome if that happens) and ```check_cutoffs``` (not troublesome, doing what the user asked for) can both end up with not producing any changes.

**Comment by ericchansen** [comment]
Can anyone confirm that commit d646465 addresses this and then close the issue?

**Comment by arosale4** [comment]
Things work well now.
